language: php

php:
  - 7

install:
  - composer install --no-interaction
  - if [ "$DEPENDENCIES" = "lowest" ]; then composer update --prefer-lowest -n; fi

script:
  - vendor/bin/phpstan analyse src tests
